# ----------------------- #
#      Main Configs       #
# ----------------------- #
url: https://junatum.com
title: JUNATUM
email: help@junatum.com
author: Junatum
description: >
  JUNATUM(준아툼)은 미국 금융 정보를 한국 사용자들이 이해하기 쉽게 한글로 제공하는 핀테크 기업입니다.
copyright: 'Copyright &copy; 2015-2022 Junatum. All Rights Reserved.'
credits: ''
ga_id: 'UA-72817395-1'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/junatumdotcom
